### PR TITLE
Updated definition of turbines, FHW, and FWH mixers

### PR DESCRIPTION
**Pull request by Andresj89**
## Fixes
The code for the definition of Turbines, FWHs, and FWH mixers have been reduced using loops and setattr()

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by Andresj89** [comment]
@nareshsusarla @jghouse88 @esrawli Guys, please have a look at this and let me know if it's on the right direction. This is WIP.

**Review by jghouse88 — COMMENTED** [review]
@Andresj89 @nareshsusarla can we merge this?

**Comment by Andresj89** [comment]
> @Andresj89 @nareshsusarla can we merge this?

I think I don't have write access to merge PRs.

**Comment by nareshsusarla** [comment]
ok i can merge this by eod today..

**Review by nareshsusarla — APPROVED** [review]

**Pull request merged**
