### PR TITLE
Model Cleanup 

### PR DESCRIPTION
**Pull request by esrawli**
- I included a README file with the commented areas in the model.
- I removed and rewrote some of the commented areas in the model.
- I added a short description to all the constraints in the model. 
- I added a process flow diagram (.svg file) to the repository and a function in the model to print out the results to this file.

### CODE REVIEW

**Comment by jghouse88** [comment]
@nareshsusarla @andresj89 can we merge this?

**Review by nareshsusarla — APPROVED** [review]
looks fine

**Comment by nareshsusarla** [comment]
i think the conflicts are because of the changes made by Andres. I am not sure how to make the changes before merging these chnages

**Comment by jghouse88** [comment]
@esrawli Can you please fix the conflicts and push again? To do this, you will have to pull naresh's branch to your existing local branch and then you will see what the conflicts are. You can approve/ignore as you see fit

**Comment by esrawli** [comment]
@jghouse88 I haven't followed all the changes @Andresj89 made to the model and I don't want to break the new stuff he added to it. Most of my changes were renaming and the addition of the svg file tags (which won't be a conflict), so I recommend @Andresj89 to resolve the conflicts since he knows the new structure and organization of the new version of the model. 
CC: @nareshsusarla

**Comment by esrawli** [comment]
@nareshsusarla I resolved the conflicts. This is ready to be merged.
CC: @jghouse88 @Andresj89

**Pull request merged**
